[chaserland-common]
manifest-path = "./Cargo.toml"
packages = ["chaserland-common"]
include-files = ["chaserland-common/src/**"]
skip-clean = true
run-types = ["Lib"]
out = ["Lcov", "Html"]
output-dir = "./coverage"
