[workspace]
resolver = "2"
members = [
    "chaserland-common",
    "chaserland-gateway",
    "chaserland-observability",
    "chaserland-protos",
    "chaserland-articles-service/crates/core",
    "chaserland-articles-service/crates/init",
    "chaserland-articles-service/crates/migrate",
    "chaserland-articles-service/crates/grpc-server",
]
