[package]
name = "chaserland-articles-service"
version = "0.1.0"
edition = "2024"
default-run = "server"

[lib]
name = "chaserland_articles_service"
path = "src/lib/lib.rs"

[[bin]]
name = "server"
path = "src/bin/server/main.rs"

[[bin]]
name = "migrate"
path = "src/bin/migrate/main.rs"

[[bin]]
name = "init"
path = "src/bin/init/main.rs"

[[bin]]
name = "trace-test"
path = "src/bin/trace-test.rs"

[dependencies]
chaserland-protos = { path = "../chaserland-protos" }
chaserland-observability = { path = "../chaserland-observability" }
chaserland-common = { path = "../chaserland-common", features = [
    "figment-file-provider",
    "pagination",
] }
tokio = { version = "1.44.1", features = [
    "macros",
    "signal",
    "rt-multi-thread",
] }
tonic = "0.13.0"
tracing = "0.1.41"
sqlx = { version = "0.8.3", features = ["chrono", "postgres", "runtime-tokio"] }
serde = { version = "1.0.219", features = ["derive"] }
chrono = { version = "0.4.40", features = ["serde"] }
anyhow = "1.0.97"
prost-types = "0.13.5"
slugify = "0.1.0"
log = "0.4.27"
async-trait = "0.1.88"
thiserror = "2.0.12"
opentelemetry = "0.29.1"
opentelemetry_sdk = { version = "0.29.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.29.0", features = ["grpc-tonic"] }
opentelemetry-semantic-conventions = { version = "0.29.0", features = [
    "semconv_experimental",
] }
tracing-opentelemetry = "0.30.0"
figment = { version = "0.10.19", features = ["env", "test"] }
clap = { version = "4.5.38", features = ["derive"] }
