[package]
name = "chaserland-articles-service"
version = "0.1.0"
edition = "2024"

[dependencies]
chaserland-protos = { path = "../chaserland-protos" }
chaserland-logger = { path = "../chaserland-logger" }
tokio = { version = "1.44.1", features = [
    "macros",
    "signal",
    "rt-multi-thread",
] }
tonic = "0.13.0"
tracing = "0.1.41"
sqlx = { version = "0.8.3", features = ["chrono", "postgres", "runtime-tokio"] }
serde = { version = "1.0.219", features = ["derive"] }
chrono = { version = "0.4.40", features = ["serde"] }
anyhow = "1.0.97"
