syntax = "proto3";

package chaserland.article.v1;

import "google/protobuf/timestamp.proto";

message CreateArticleRequest {
  ArticleCreate article = 1;
}

message CreateArticleResponse {
  Article article = 1;
}

message CreateSeriesRequest {
  SeriesCreate series = 1;
}

message CreateSeriesResponse {
  Series series = 1;
}

message CreateCategoryRequest {
  CategoryCreate category = 1;
}

message CreateCategoryResponse {
  Category category = 1;
}

message CreateTagRequest {
  TagCreate tag = 1;
}

message CreateTagResponse {
  Tag tag = 1;
}

message GetArticleOneRequest {
  ArticleIdentifier identifier = 1;
  bool public_only = 2;
  bool with_content = 3;
}

message GetArticleOneResponse {
  Article article = 1;
}

message GetArticleManyRequest {
  int32 page = 1;
  int32 page_size = 2;
  bool public_only = 3;
  bool with_content = 4;
  ArticlesFilter filter = 5;
}

message ArticlesFilter {
  optional SeriesIdentifier series_identifier = 1;
  repeated int32 category_ids = 2;
  repeated int32 tag_ids = 3;
}

message GetArticleManyResponse {
  repeated Article articles = 1;
}

message GetArticleContentRequest {
  ArticleIdentifier identifier = 1;
  bool public_only = 2;
}

message GetArticleContentResponse {
  string content = 1;
}

message GetSeriesOneRequest {
  SeriesIdentifier identifier = 1;
}

message GetSeriesOneResponse {
  Series series = 1;
}

message GetSeriesManyRequest {

}

message GetSeriesManyResponse {
  repeated Series series = 1;
}

message GetCategoryOneRequest {
  CategoryIdentifier identifier = 1;
}

message GetCategoryOneResponse {
  Category category = 1;
}

message GetCategoryManyRequest {

}

message GetCategoryManyResponse {
  repeated Category categories = 1;
}

message GetTagOneRequest {
  TagIdentifier identifier = 1;
}

message GetTagOneResponse {
  Tag tag = 1;
}

message GetTagManyRequest {

}

message GetTagManyResponse {
  repeated Tag tags = 1;
}

message PublishArticleRequest {
  ArticleIdentifier identifier = 1;
}

message PublishArticleResponse {

}

message UnpublishArticleRequest {
  ArticleIdentifier identifier = 1;
}

message UnpublishArticleResponse {
  
}

message SoftDeleteArticleRequest {
  ArticleIdentifier identifier = 1;
}

message SoftDeleteArticleResponse {
  
}

message RevokeSoftDeleteArticleRequest {
  ArticleIdentifier identifier = 1;
}

message RevokeSoftDeleteArticleResponse {
  
}

message DeleteArticleRequest {
  ArticleIdentifier identifier = 1;
}

message DeleteArticleResponse {
  
}

message DeleteSeriesRequest {
  SeriesIdentifier identifier = 1;
}

message DeleteSeriesResponse {
  
}

message DeleteCategoryRequest {
  CategoryIdentifier identifier = 1;
}

message DeleteCategoryResponse {
  
}

message DeleteTagRequest {
  TagIdentifier identifier = 1;
}

message DeleteTagResponse {
  
}

message Series {
  int32 id = 1;
  string slug = 2;
  string name = 3;
}

message SeriesIdentifier {
  oneof identifier {
    int32 id = 1;
    string slug = 2;
  }
}

message SeriesCreate {
  string name = 1;
}

message Tag {
  int32 id = 1;
  string name = 2;
  string slug = 3;
}

message TagIdentifier {
  oneof identifier {
    int32 id = 1;
    string slug = 2;
  }
}

message TagCreate {
  string name = 1;
}

message Category {
  int32 id = 1;
  string name = 2;
  string slug = 3;
}

message CategoryIdentifier {
  oneof identifier {
    int32 id = 1;
    string slug = 2;
  }
}

message CategoryCreate {
  string name = 1;
}

message Article {
  int32 id = 1;
  string title = 2;
  string slug = 3;
  string description = 4;
  optional string content = 5;
  optional Series series = 6;
  repeated Category categories = 7;
  repeated Tag tags = 8;
  google.protobuf.Timestamp created_at = 9;
  optional google.protobuf.Timestamp published_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  optional google.protobuf.Timestamp deleted_at = 12;
}

message ArticleIdentifier {
  oneof identifier {
    int32 id = 1;
    string slug = 2;
  }
}

message ArticleCreate {
  string title = 1;
  string description = 2;
  string content = 3;
  optional int32 series_id = 4;
  repeated int32 category_ids = 5;
  repeated int32 tag_ids = 6;
}
