syntax = "proto3";

package chaserland.article.v1;

import "chaserland/article/v1/article.proto";

service ArticleService {
  rpc CreateArticle (CreateArticleRequest) returns (CreateArticleResponse);
  rpc CreateSeries (CreateSeriesRequest) returns (CreateSeriesResponse);
  rpc CreateCategory (CreateCategoryRequest) returns (CreateCategoryResponse);
  rpc CreateTag (CreateTagRequest) returns (CreateTagResponse);

  rpc GetArticleOne (GetArticleOneRequest) returns (GetArticleOneResponse);
  rpc GetArticleContent (GetArticleContentRequest)
    returns (GetArticleContentResponse);
  rpc GetArticleMany (GetArticleManyRequest) returns (GetArticleManyResponse);
  rpc GetSeriesOne (GetSeriesOneRequest) returns (GetSeriesOneResponse);
  rpc GetSeriesMany (GetSeriesManyRequest) returns (GetSeriesManyResponse);
  rpc GetCategoryOne (GetCategoryOneRequest) returns (GetCategoryOneResponse);
  rpc GetCategoryMany (GetCategoryManyRequest)
    returns (GetCategoryManyResponse);
  rpc GetTagOne (GetTagOneRequest) returns (GetTagOneResponse);
  rpc GetTagMany (GetTagManyRequest) returns (GetTagManyResponse);

  rpc PublishArticle (PublishArticleRequest)
    returns (PublishArticleResponse);
  rpc UnpublishArticle (UnpublishArticleRequest)
    returns (UnpublishArticleResponse);
  rpc SoftDeleteArticle (SoftDeleteArticleRequest)
    returns (SoftDeleteArticleResponse);
  rpc RevokeSoftDeleteArticle (RevokeSoftDeleteArticleRequest)
    returns (RevokeSoftDeleteArticleResponse);

  rpc DeleteArticle (DeleteArticleRequest) 
    returns (DeleteArticleResponse);
  rpc DeleteSeries (DeleteSeriesRequest)
    returns (DeleteSeriesResponse);
  rpc DeleteCategory (DeleteCategoryRequest)
    returns (DeleteCategoryResponse);
  rpc DeleteTag (DeleteTagRequest) returns (DeleteTagResponse);
}


