[package]
name = "chaserland-articles-service-rest-server"
version = "0.1.0"
edition = "2024"

[dependencies]
chaserland-articles-service-core = { path = "../core" }
chaserland-observability = { path = "../../../chaserland-observability" }
chaserland-common = { path = "../../../chaserland-common", features = [
    "figment-file-provider",
] }
anyhow = "1.0.97"
serde = { version = "1.0.219", features = ["derive"] }
figment = { version = "0.10.19", features = ["env", "test"] }
tokio = { version = "1.44.1", features = [
    "macros",
    "signal",
    "rt-multi-thread",
] }
tracing = "0.1.41"
tracing-opentelemetry = "0.31.0"
opentelemetry = "0.30.0"
opentelemetry-http = "0.30.0"
axum = "0.8.4"
clap = { version = "4.5.38", features = ["derive"] }
tower-http = { version = "0.6.4", features = ["trace"] }
tower = "0.5.2"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"
