[package]
name = "chaserland-articles-service-init"
version = "0.1.0"
edition = "2024"

[dependencies]
chaserland-articles-service-server = { path = "../server" }
chaserland-observability = { path = "../../../chaserland-observability" }
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
sqlx = { version = "0.8.6", features = ["chrono", "postgres", "runtime-tokio"] }
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.97"
figment = { version = "0.10.19", features = ["env", "test"] }
