[package]
name = "chaserland-articles-service-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chaserland-protos = { path = "../../../chaserland-protos" }
chaserland-observability = { path = "../../../chaserland-observability" }
chaserland-common = { path = "../../../chaserland-common", features = [
    "pagination",
] }
chaserland-articles-service-migrate = { path = "../migrate" }
tonic = "0.13.1"
tracing = "0.1.41"
sqlx = { version = "0.8.6", features = [
    "chrono",
    "postgres",
    "runtime-tokio",
    "migrate",
] }
serde = { version = "1.0.219", features = ["derive"] }
chrono = { version = "0.4.40", features = ["serde"] }
anyhow = "1.0.97"
prost-types = "0.13.5"
slugify = "0.1.0"
log = "0.4.27"
thiserror = "2.0.12"
opentelemetry = "0.30.0"
tower = "0.5.2"
http = "1.3.1"
tower-http = { version = "0.6.4", features = ["trace"] }
axum = "0.8.4"
axum-extra = { version = "0.10.1", features = ["query"] }
utoipa = { version = "5.4.0", features = ["axum_extras"] }
utoipa-axum = "0.2.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
utoipa-redoc = { version = "6.0.0", features = ["axum"] }
utoipa-rapidoc = { version = "6.0.0", features = ["axum"] }
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
trait-variant = "0.1.2"

[features]
app-integration-tests = []
infra-postgres-integration-tests = []
