[chaserland-articles-service]
manifest-path = "./Cargo.toml"
include-files = ["chaserland-articles-service/crates/core/src/**"]
skip-clean = true
run-types = ["Lib"]

[report]
out = ["Lcov", "Html"]
output-dir = "./coverage"
